from __future__ import annotations

from raceweek.core.models import TemplateType

HEADER_ALIASES: dict[str, set[str]] = {
    "season": {"season", "year", "f1_season"},
    "round": {"round", "race_round", "gp_round", "event_round"},
    "event_id": {"event_id", "event", "race_id", "raceweek_id"},
    "asset_id": {"asset_id", "assetid", "id"},
    "out_asset_id": {"out_asset_id", "asset_out_id", "out_id"},
    "in_asset_id": {"in_asset_id", "asset_in_id", "in_id"},
    "out_display_name": {"out_display_name", "out_name", "asset_out_name"},
    "in_display_name": {"in_display_name", "in_name", "asset_in_name"},
    "asset_name": {
        "asset_name",
        "display_name",
        "name",
        "driver",
        "constructor",
        "team",
        "asset",
    },
    "asset_kind": {"asset_kind", "kind", "type", "asset_type", "driver_constructor"},
    "team_name": {"team_name", "entry_name", "constructor", "racing_team", "f1_team"},
    "short_name": {"short_name", "shortname", "abbr", "abbreviation", "code", "tla"},
    "team_color": {"team_color", "team_colour", "teamcolor", "color", "colour", "color_hex"},
    "price_m": {"price_m", "price", "cost", "value", "current_price", "price_millions"},
    "fantasy_points_total": {"fantasy_points_total", "official_fantasy_points", "points", "score"},
    "selection_percent": {
        "selection_percent",
        "ownership_pct",
        "selected_by_pct",
        "ownership",
        "selected_by",
        "picked_by",
        "selection",
    },
    "cost_cap_m": {"cost_cap_m", "cost_cap_millions", "cost_cap", "cap", "budget_cap"},
    "budget_used_m": {"budget_used_m", "budget_used_millions", "spent_m", "spent"},
    "bank_m": {
        "bank_m",
        "budget_remaining_millions",
        "bank",
        "remaining_budget",
        "budget_remaining",
    },
    "free_transfers": {"free_transfers", "transfers", "ft"},
    "transfer_penalty_points": {"transfer_penalty_points", "transfer_penalty", "hit_points"},
    "penalty_points": {"penalty_points", "points_hit", "hit"},
    "transfer_number": {"transfer_number", "transfer_no", "transfer"},
    "chip_name": {"chip_name", "chip"},
    "chip_status": {"status", "chip_status"},
    "chip_active": {"chip_active", "active_chip"},
    "used_event_id": {"used_event_id", "used_round_event_id"},
    "slot_type": {"slot_type", "type", "asset_type", "kind"},
    "slot_number": {"slot_number", "slot", "lineup_slot"},
    "league_id": {"league_id", "league"},
    "league_name": {"league_name"},
    "league_rank": {"league_rank", "rank", "position", "league_position"},
    "overall_rank": {"overall_rank", "global_rank"},
    "round_points": {"round_points", "event_points"},
    "manager_name": {"manager_name", "manager"},
    "total_points": {"total_points", "points", "score"},
    "asset_ids": {"asset_ids", "assets", "lineup", "selected_assets"},
    "boost_multiplier": {"boost_multiplier", "multiplier", "boost"},
    "source_note": {"source_note", "note", "notes"},
}

REQUIRED_COLUMNS: dict[TemplateType, set[str]] = {
    "team_state": {"team_name", "cost_cap_m", "bank_m", "free_transfers"},
    "team_slots": {"slot_number", "asset_name"},
    "market_prices": {"asset_kind", "asset_name", "price_m"},
    "fantasy_scores": {"asset_name", "fantasy_points_total"},
    "league_table": {"league_rank", "team_name", "total_points"},
    "chips_state": {"chip_name", "chip_status"},
    "season_totals": {"team_name", "total_points"},
    "transfer_history_optional": {"transfer_number", "in_asset_id"},
    "rival_team_slots": {"league_id", "team_name", "league_rank", "asset_id", "asset_kind"},
}
